<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ServiceCategory;
use Illuminate\Support\Str;

class ServiceCategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            [
                'name' => 'Air Conditioning Repair',
                'name_ar' => 'صيانة وإصلاح المكيفات',
                'slug' => 'air-conditioning-repair',
                'description' => 'Air conditioning maintenance, repair and cleaning services',
                'description_ar' => 'خدمات صيانة وإصلاح وتنظيف جميع أنواع المكيفات',
                'icon' => 'bi-snow',
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Plumbing Services',
                'name_ar' => 'السباكة وأعمال السباكة',
                'slug' => 'plumbing-services',
                'description' => 'Plumbing services and leak repairs',
                'description_ar' => 'خدمات السباكة والصيانة وإصلاح التسريبات',
                'icon' => 'bi-droplet',
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Electrical Services',
                'name_ar' => 'الكهرباء والكهربائيات',
                'slug' => 'electrical-services',
                'description' => 'Electrical services and maintenance',
                'description_ar' => 'خدمات الكهرباء والصيانة الكهربائية',
                'icon' => 'bi-lightning-charge',
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Carpentry & Furniture',
                'name_ar' => 'النجارة والأثاث',
                'slug' => 'carpentry-furniture',
                'description' => 'Furniture manufacturing, repair and maintenance',
                'description_ar' => 'صناعة وإصلاح وصيانة الأثاث والنجارة',
                'icon' => 'bi-hammer',
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Painting & Decoration',
                'name_ar' => 'الدهان والديكور',
                'slug' => 'painting-decoration',
                'description' => 'Interior and exterior painting and decoration services',
                'description_ar' => 'خدمات الدهان والديكور الداخلي والخارجي',
                'icon' => 'bi-paint-bucket',
                'is_active' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'Cleaning Services',
                'name_ar' => 'التنظيف والنظافة',
                'slug' => 'cleaning-services',
                'description' => 'Residential and commercial cleaning services',
                'description_ar' => 'خدمات التنظيف المنزلي والتجاري',
                'icon' => 'bi-sparkles',
                'is_active' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Pest Control',
                'name_ar' => 'مكافحة الحشرات',
                'slug' => 'pest-control',
                'description' => 'Pest and rodent control services',
                'description_ar' => 'خدمات مكافحة الحشرات والقوارض',
                'icon' => 'bi-bug',
                'is_active' => true,
                'sort_order' => 7,
            ],
            [
                'name' => 'Furniture Moving',
                'name_ar' => 'نقل الأثاث والعفش',
                'slug' => 'furniture-moving',
                'description' => 'Furniture and household moving services',
                'description_ar' => 'خدمات نقل الأثاث والعفش المنزلي',
                'icon' => 'bi-truck',
                'is_active' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'Delivery Services',
                'name_ar' => 'خدمات التوصيل',
                'slug' => 'delivery-services',
                'description' => 'Fast delivery and transportation services',
                'description_ar' => 'خدمات التوصيل والنقل السريع',
                'icon' => 'bi-box-seam',
                'is_active' => true,
                'sort_order' => 9,
            ],
            [
                'name' => 'Home Appliances Repair',
                'name_ar' => 'صيانة الأجهزة المنزلية',
                'slug' => 'home-appliances-repair',
                'description' => 'Repair and maintenance of all home appliances',
                'description_ar' => 'إصلاح وصيانة جميع الأجهزة المنزلية',
                'icon' => 'bi-tools',
                'is_active' => true,
                'sort_order' => 10,
            ],
            [
                'name' => 'Metalwork & Aluminum',
                'name_ar' => 'الحدادة والألمنيوم',
                'slug' => 'metalwork-aluminum',
                'description' => 'Metalwork, aluminum and door services',
                'description_ar' => 'أعمال الحدادة والألمنيوم والأبواب',
                'icon' => 'bi-door-closed',
                'is_active' => true,
                'sort_order' => 11,
            ],
            [
                'name' => 'Glass & Mirrors',
                'name_ar' => 'الزجاج والمرايا',
                'slug' => 'glass-mirrors',
                'description' => 'Glass and mirror installation and maintenance',
                'description_ar' => 'تركيب وصيانة الزجاج والمرايا',
                'icon' => 'bi-window',
                'is_active' => true,
                'sort_order' => 12,
            ],
            [
                'name' => 'Tiles & Ceramics',
                'name_ar' => 'البلاط والسيراميك',
                'slug' => 'tiles-ceramics',
                'description' => 'Tile and ceramic installation and maintenance',
                'description_ar' => 'تركيب وصيانة البلاط والسيراميك',
                'icon' => 'bi-grid-3x3-gap',
                'is_active' => true,
                'sort_order' => 13,
            ],
            [
                'name' => 'Auto Painting',
                'name_ar' => 'السباغة والدوكو',
                'slug' => 'auto-painting',
                'description' => 'Car painting and coating services',
                'description_ar' => 'خدمات سباغة وطلاء السيارات',
                'icon' => 'bi-car-front',
                'is_active' => true,
                'sort_order' => 14,
            ],
            [
                'name' => 'Auto Mechanics',
                'name_ar' => 'ميكانيكا السيارات',
                'slug' => 'auto-mechanics',
                'description' => 'Car maintenance and repair',
                'description_ar' => 'صيانة وإصلاح السيارات',
                'icon' => 'bi-wrench',
                'is_active' => true,
                'sort_order' => 15,
            ],
            [
                'name' => 'Car Wash',
                'name_ar' => 'غسيل السيارات',
                'slug' => 'car-wash',
                'description' => 'Car washing and cleaning services',
                'description_ar' => 'خدمات غسيل وتنظيف السيارات',
                'icon' => 'bi-water',
                'is_active' => true,
                'sort_order' => 16,
            ],
            [
                'name' => 'Landscaping',
                'name_ar' => 'تنسيق الحدائق',
                'slug' => 'landscaping',
                'description' => 'Garden design, landscaping and maintenance',
                'description_ar' => 'تصميم وتنسيق وصيانة الحدائق',
                'icon' => 'bi-tree',
                'is_active' => true,
                'sort_order' => 17,
            ],
            [
                'name' => 'Photography Services',
                'name_ar' => 'خدمات التصوير',
                'slug' => 'photography-services',
                'description' => 'Photography and videography services',
                'description_ar' => 'التصوير الفوتوغرافي والفيديو',
                'icon' => 'bi-camera',
                'is_active' => true,
                'sort_order' => 18,
            ],
            [
                'name' => 'Tutoring',
                'name_ar' => 'التدريس والدروس الخصوصية',
                'slug' => 'tutoring',
                'description' => 'Private tutoring in all subjects',
                'description_ar' => 'دروس خصوصية في جميع المواد',
                'icon' => 'bi-book',
                'is_active' => true,
                'sort_order' => 19,
            ],
            [
                'name' => 'Computer & IT Services',
                'name_ar' => 'خدمات الكمبيوتر والتقنية',
                'slug' => 'computer-it-services',
                'description' => 'Computer and network maintenance',
                'description_ar' => 'صيانة الكمبيوتر والشبكات',
                'icon' => 'bi-laptop',
                'is_active' => true,
                'sort_order' => 20,
            ],
            [
                'name' => 'Tailoring & Sewing',
                'name_ar' => 'الخياطة والتفصيل',
                'slug' => 'tailoring-sewing',
                'description' => 'Tailoring and clothing alteration services',
                'description_ar' => 'خدمات الخياطة وتفصيل الملابس',
                'icon' => 'bi-scissors',
                'is_active' => true,
                'sort_order' => 21,
            ],
            [
                'name' => 'Cooking & Catering',
                'name_ar' => 'الطبخ والطهي',
                'slug' => 'cooking-catering',
                'description' => 'Home cooking and catering services',
                'description_ar' => 'خدمات الطبخ والطهي المنزلي',
                'icon' => 'bi-egg-fried',
                'is_active' => true,
                'sort_order' => 22,
            ],
            [
                'name' => 'Event Services',
                'name_ar' => 'خدمات المناسبات',
                'slug' => 'event-services',
                'description' => 'Event organizing and setup services',
                'description_ar' => 'تنظيم وتجهيز المناسبات والحفلات',
                'icon' => 'bi-gift',
                'is_active' => true,
                'sort_order' => 23,
            ],
            [
                'name' => 'Personal Care',
                'name_ar' => 'العناية الشخصية',
                'slug' => 'personal-care',
                'description' => 'Hairdressing and beauty services',
                'description_ar' => 'خدمات الحلاقة والتجميل',
                'icon' => 'bi-person',
                'is_active' => true,
                'sort_order' => 24,
            ],
            [
                'name' => 'Home Healthcare',
                'name_ar' => 'الرعاية الصحية المنزلية',
                'slug' => 'home-healthcare',
                'description' => 'Home healthcare services',
                'description_ar' => 'خدمات الرعاية الصحية في المنزل',
                'icon' => 'bi-heart-pulse',
                'is_active' => true,
                'sort_order' => 25,
            ],
            [
                'name' => 'Pet Services',
                'name_ar' => 'خدمات الحيوانات الأليفة',
                'slug' => 'pet-services',
                'description' => 'Pet care and training services',
                'description_ar' => 'رعاية وتدريب الحيوانات الأليفة',
                'icon' => 'bi-paw',
                'is_active' => true,
                'sort_order' => 26,
            ],
            [
                'name' => 'Security Services',
                'name_ar' => 'الأمن والحراسة',
                'slug' => 'security-services',
                'description' => 'Security and guard services',
                'description_ar' => 'خدمات الأمن والحراسة',
                'icon' => 'bi-shield-check',
                'is_active' => true,
                'sort_order' => 27,
            ],
            [
                'name' => 'Waterproofing & Insulation',
                'name_ar' => 'عزل الأسطح والخزانات',
                'slug' => 'waterproofing-insulation',
                'description' => 'Waterproofing and thermal insulation services',
                'description_ar' => 'خدمات العزل المائي والحراري',
                'icon' => 'bi-house',
                'is_active' => true,
                'sort_order' => 28,
            ],
            [
                'name' => 'Curtains & Blinds',
                'name_ar' => 'تركيب الستائر والبراقع',
                'slug' => 'curtains-blinds',
                'description' => 'Curtain installation and maintenance',
                'description_ar' => 'تركيب وصيانة الستائر',
                'icon' => 'bi-layout-sidebar',
                'is_active' => true,
                'sort_order' => 29,
            ],
            [
                'name' => 'Other Services',
                'name_ar' => 'خدمات أخرى',
                'slug' => 'other-services',
                'description' => 'Various other services',
                'description_ar' => 'خدمات متنوعة أخرى',
                'icon' => 'bi-three-dots',
                'is_active' => true,
                'sort_order' => 30,
            ],
        ];

        foreach ($categories as $category) {
            ServiceCategory::updateOrCreate(
                ['slug' => $category['slug']],
                $category
            );
        }

        $this->command->info('تم إضافة ' . count($categories) . ' تصنيف للخدمات بنجاح!');
    }
}
